# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: gcr.io/qwiklabs-gcp-00-393f9f205c58/kubernetesproject:1.0
        ports:
        - containerPort: 4000