# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 4000
  type: LoadBalancer